### ISSUE TITLE
Doesn't seem to work with OpenShift 4.11.0

### ISSUE THREAD

**Issue by jwilms1971** [openshift/predictive-vpa-recommenders#2]
After adding anyuid SCC permissions on my 4.11.0 cluster I was able to get the pods running with userid 65534, but it seems that the custom VPA is not recommending anything. Please see the output below.

$ oc get pods
NAME                             READY   STATUS    RESTARTS   AGE
test-periodic-6db95b9878-6hhht   1/1     Running   0          2m44s
test-periodic-6db95b9878-f7vxf   1/1     Running   0          2m44s

$ oc logs test-periodic-6db95b9878-6hhht
Modular seconds over 1200 seconds: 250
Idle for 1140 seconds!
Modular seconds over 1200 seconds: 251
Idle for 1140 seconds!
Modular seconds over 1200 seconds: 252
Idle for 1140 seconds!
Modular seconds over 1200 seconds: 253
Idle for 1140 seconds!

$ oc adm top pods
NAME                             CPU(cores)   MEMORY(bytes)   
test-periodic-6db95b9878-6hhht   1m           0Mi             
test-periodic-6db95b9878-f7vxf   1m           0Mi   

$ oc get vpa
NAME                MODE   CPU   MEM   PROVIDED   AGE
test-periodic-vpa   Auto                          4m33s

$ oc logs -f pando-644c5d9958-g6lzz -n openshift-vertical-pod-autoscaler
{'recommenders': [{'name': 'pando'}], 'resourcePolicy': {'containerPolicies': [{'containerName': '*', 'controlledResources': ['cpu', 'memory'], 'maxAllowed': {'cpu': 2, 'memory': '1Gi'}, 'minAllowed': {'cpu': '100m', 'memory': '50Mi'}}]}, 'targetRef': {'apiVersion': 'apps/v1', 'kind': 'Deployment', 'name': 'test-periodic'}, 'updatePolicy': {'updateMode': 'Auto'}}
{'apiVersion': 'apps/v1', 'kind': 'Deployment', 'name': 'test-periodic'}
No new recommendations obtained, so skip updating the vpa object test-periodic-vpa

**Comment by wangchen615** [comment]
@jwilms1971 , thanks for reporting this.
It seems pando recommender was not able to fetch prometheus data correctly. I am debugging the configuration issues.
